"""
Scrabble board: 15x15 grid with premium squares.

Premium square encoding:
  DL = double letter, TL = triple letter
  DW = double word,   TW = triple word
"""

from dataclasses import dataclass, field
from typing import Optional

# Premium square layout for the top-left quadrant (rows 0-7, cols 0-7).
# The full board is generated by 4-fold symmetry.
_QUAD_PREMIUMS = {
    (0, 0): "TW", (0, 3): "DL", (0, 7): "TW",
    (1, 1): "DW", (1, 5): "TL",
    (2, 2): "DW", (2, 6): "DL",
    (3, 0): "DL", (3, 3): "DW",
    (4, 4): "DW",
    (5, 1): "TL", (5, 5): "TL",
    (6, 2): "DL", (6, 6): "DL",
    (7, 0): "TW", (7, 3): "DL", (7, 7): "DW",  # centre is DW (star)
}


def _build_premium_map() -> dict[tuple[int, int], str]:
    """Expand quadrant premiums to the full 15x15 board via symmetry."""
    premiums: dict[tuple[int, int], str] = {}
    for (r, c), kind in _QUAD_PREMIUMS.items():
        for row in (r, 14 - r):
            for col in (c, 14 - c):
                premiums[(row, col)] = kind
    return premiums


PREMIUM = _build_premium_map()

# Tile scores (standard Scrabble)
TILE_SCORES: dict[str, int] = {
    "A": 1,  "B": 3,  "C": 3,  "D": 2,  "E": 1,
    "F": 4,  "G": 2,  "H": 4,  "I": 1,  "J": 8,
    "K": 5,  "L": 1,  "M": 3,  "N": 1,  "O": 1,
    "P": 3,  "Q": 10, "R": 1,  "S": 1,  "T": 1,
    "U": 1,  "V": 4,  "W": 4,  "X": 8,  "Y": 4,
    "Z": 10, "?": 0,  # "?" = blank tile
}

# Standard tile distribution
TILE_DISTRIBUTION: dict[str, int] = {
    "A": 9, "B": 2, "C": 2, "D": 4, "E": 12, "F": 2,
    "G": 3, "H": 2, "I": 9, "J": 1, "K": 1,  "L": 4,
    "M": 2, "N": 6, "O": 8, "P": 2, "Q": 1,  "R": 6,
    "S": 4, "T": 6, "U": 4, "V": 2, "W": 2,  "X": 1,
    "Y": 2, "Z": 1, "?": 2,
}


@dataclass
class Square:
    """One cell on the board."""
    tile: Optional[str] = None       # uppercase letter, or None if empty
    is_blank: bool = False           # True if tile came from a blank


class Board:
    """
    15x15 Scrabble board.

    Coordinates: board[row][col], row 0 = top, col 0 = left.
    Centre square = (7, 7).
    """

    SIZE = 15
    CENTER = (7, 7)

    def __init__(self) -> None:
        self.grid: list[list[Square]] = [
            [Square() for _ in range(self.SIZE)]
            for _ in range(self.SIZE)
        ]

    def is_empty(self) -> bool:
        return all(
            self.grid[r][c].tile is None
            for r in range(self.SIZE)
            for c in range(self.SIZE)
        )

    def get(self, row: int, col: int) -> Square:
        return self.grid[row][col]

    def place_tile(self, row: int, col: int, letter: str, is_blank: bool = False) -> None:
        """Place a single tile. Call this for each tile in a move."""
        sq = self.grid[row][col]
        if sq.tile is not None:
            raise ValueError(f"Square ({row},{col}) already occupied by '{sq.tile}'")
        sq.tile = letter.upper()
        sq.is_blank = is_blank

    def remove_tile(self, row: int, col: int) -> tuple[str, bool]:
        """Remove a tile and return (letter, is_blank). Used for undoing moves."""
        sq = self.grid[row][col]
        if sq.tile is None:
            raise ValueError(f"Square ({row},{col}) is empty")
        letter, blank = sq.tile, sq.is_blank
        sq.tile = None
        sq.is_blank = False
        return letter, blank

    def premium(self, row: int, col: int) -> Optional[str]:
        """Return premium type for a square, or None. Premiums apply only when first covered."""
        if self.grid[row][col].tile is None:
            return PREMIUM.get((row, col))
        return None  # already occupied — premium already used

    def neighbours(self, row: int, col: int) -> list[tuple[int, int]]:
        result = []
        for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            r, c = row + dr, col + dc
            if 0 <= r < self.SIZE and 0 <= c < self.SIZE:
                result.append((r, c))
        return result

    def has_adjacent_tile(self, row: int, col: int) -> bool:
        return any(
            self.grid[r][c].tile is not None
            for r, c in self.neighbours(row, col)
        )

    def display(self) -> str:
        """Return a printable board string."""
        PREMIUM_SYMBOLS = {"TW": "**", "DW": "* ", "TL": "##", "DL": "# "}
        lines = ["   " + " ".join(f"{c:2}" for c in range(self.SIZE))]
        for r in range(self.SIZE):
            row_parts = []
            for c in range(self.SIZE):
                sq = self.grid[r][c]
                if sq.tile:
                    ch = sq.tile.lower() if sq.is_blank else sq.tile
                    row_parts.append(f"{ch:>2}")
                else:
                    sym = PREMIUM_SYMBOLS.get(PREMIUM.get((r, c), ""), ". ")
                    row_parts.append(sym)
            lines.append(f"{r:2} " + " ".join(row_parts))
        return "\n".join(lines)

    def __repr__(self) -> str:  # pragma: no cover
        return self.display()
